### ISSUE TITLE
Launching Crash : Duplicated Mods #2

### ISSUE THREAD

**Issue by lays24mc** [JadedPacks/Agrarian-Skies#4]
## Steps to Reproduce

Thank for your 4.0.2 update, but the server crashed now with the same error in 4.0.0 :/. Mods are not duplicated!

## Logs

* Crash Log: https://pastebin.com/4GWAF3ED

## Client Information

* Modpack Version: 4.0.2
* Server/LAN/Single Player: Server

**Comment by ghost** [comment]
Either update JadedLibs, or disable it. Should fix the problem for now, till I get 4.0.3 out.

**Comment by ghost** [comment]
Fixed as of https://github.com/JadedPacks/Agrarian-Skies/commit/2a5924ef1855c924cecec0536ff09d4371fe1d83

**Comment by lays24mc** [comment]
Same in 4.0.3 :/

> Description: Exception in server tick loop

cpw.mods.fml.common.DuplicateModsFoundException
	at cpw.mods.fml.common.Loader.identifyDuplicates(Loader.java:396)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:354)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:484)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:69)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

**Comment by ghost** [comment]
This is very persistent lol. Disable jaded libs for the time being till I
work out what wrench went in the code :)

**Comment by ghost** [comment]
Having stared at how FML loads in 1.6.4, this has been resolved (I was too used to 1.7.2+ mechanics).

Fixed in next version.
